version: '3.8'

services: 
  postgres:
    container_name: db_post_comment
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
    volumes:
          #Formation of a database with values ​​for testing.
      - ./postgresdb/sql/PostsComments.sql:/docker-entrypoint-initdb.d/PostsComments.sql
          #Formation of an empty database with a table structure.
    # - ./postgresdb/sql/EmptyDB.sql:/docker-entrypoint-initdb.d/EmptyDB.sql
    image: postgres:16.2-alpine3.19

  intertask:
    container_name: intertask
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgres://admin:12345@postgres:5432/db_post_comment?sslmode=disable
      - IN_MEMORY=false
    build:
      context: .

networks:
  default: