CREATE DATABASE db_post_comment;
\connect db_post_comment

CREATE TABLE "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(128)
);

CREATE TABLE "posts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "text" text,
  "userid" integer,
  "cancomment" boolean,
  FOREIGN KEY (userid) REFERENCES users(id)
);

CREATE TABLE "comments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userid" integer,
  "text" varchar(2000),
  "postid" integer,
  "perentid" integer,
  FOREIGN KEY (userid) REFERENCES users(id),
  FOREIGN KEY (postid) REFERENCES posts(id),
  FOREIGN KEY (perentid) REFERENCES comments(id)
);
