CREATE DATABASE db_post_comment;
\connect db_post_comment

CREATE TABLE "users" (
  "uid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(128)
);

CREATE TABLE "posts" (
  "pid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ptext" text,
  "postAuthorID" integer,
  "canComment" boolean
);

CREATE TABLE "comments" (
  "cid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userID" integer,
  "ctext" varchar(2000),
  "postID" integer,
  "perentID" integer
);

CREATE TABLE "userSubscription" (
  "userID" integer,
  "postID" integer
);

CREATE INDEX ON "comments" ("postID", "perentID");

ALTER TABLE "posts" ADD FOREIGN KEY ("postAuthorID") REFERENCES "users" ("uid");

ALTER TABLE "comments" ADD FOREIGN KEY ("postID") REFERENCES "posts" ("pid");

ALTER TABLE "comments" ADD FOREIGN KEY ("userID") REFERENCES "users" ("uid");

ALTER TABLE "comments" ADD FOREIGN KEY ("perentID") REFERENCES "comments" ("cid");

ALTER TABLE "userSubscription" ADD FOREIGN KEY ("userID") REFERENCES "users" ("uid");

ALTER TABLE "userSubscription" ADD FOREIGN KEY ("postID") REFERENCES "posts" ("pid");


INSERT INTO "users" (name) VALUES ('Пользователь_1');
INSERT INTO "users" (name) VALUES ('Пользователь_2');
INSERT INTO "users" (name) VALUES ('Пользователь_3');
INSERT INTO "users" (name) VALUES ('Пользователь_4');
INSERT INTO "users" (name) VALUES ('Пользователь_5');
INSERT INTO "users" (name) VALUES ('Пользователь_6');
INSERT INTO "users" (name) VALUES ('Пользователь_7');
INSERT INTO "users" (name) VALUES ('Пользователь_8');
INSERT INTO "users" (name) VALUES ('Пользователь_9');
INSERT INTO "users" (name) VALUES ('Пользователь_10');
INSERT INTO "users" (name) VALUES ('Пользователь_11');
INSERT INTO "users" (name) VALUES ('Пользователь_12');
INSERT INTO "users" (name) VALUES ('Пользователь_13');
INSERT INTO "users" (name) VALUES ('Пользователь_14');
INSERT INTO "users" (name) VALUES ('Пользователь_15');
INSERT INTO "users" (name) VALUES ('Пользователь_16');
INSERT INTO "users" (name) VALUES ('Пользователь_17');
INSERT INTO "users" (name) VALUES ('Пользователь_18');
INSERT INTO "users" (name) VALUES ('Пользователь_19');
INSERT INTO "users" (name) VALUES ('Пользователь_20');
INSERT INTO "users" (name) VALUES ('Пользователь_21');
INSERT INTO "users" (name) VALUES ('Пользователь_22');


INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 1', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_1';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 2', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_1';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 3', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_1';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 4', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_1';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_3';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 5', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_3';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 6', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_5';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 7', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_5';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 8', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_7';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 9', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_9';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 10', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_9';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 11', 'false', uid
FROM users 
WHERE "name" = 'Пользователь_11';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 12', 'false', uid
FROM users 
WHERE "name" = 'Пользователь_11';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 13', 'false', uid
FROM users 
WHERE "name" = 'Пользователь_13';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 14', 'false', uid
FROM users 
WHERE "name" = 'Пользователь_13';

INSERT INTO posts ("ptext", "canComment", "postAuthorID") 
SELECT 'Текст поста 15', 'true', uid
FROM users 
WHERE "name" = 'Пользователь_13';




INSERT INTO comments ("ctext", "userID", "postID") 
SELECT 'Текст каментария 00', "uid", "pid"
FROM users, posts
WHERE "name" = 'Пользователь_2' AND "ptext" = 'Текст поста 1';

INSERT INTO comments ("ctext", "userID", "postID") 
SELECT 'Текст каментария 10', "uid", "pid"
FROM users, posts
WHERE "name" = 'Пользователь_4' AND "ptext" = 'Текст поста 1';

INSERT INTO comments ("ctext", "userID", "postID") 
SELECT 'Текст каментария 20', "uid", "pid"
FROM users, posts
WHERE "name" = 'Пользователь_6' AND "ptext" = 'Текст поста 1';

INSERT INTO comments ("ctext", "userID", "postID") 
SELECT 'Текст каментария 30', "uid", "pid"
FROM users, posts
WHERE "name" = 'Пользователь_8' AND "ptext" = 'Текст поста 1';

INSERT INTO comments ("ctext", "userID", "postID", "perentID") 
SELECT 'Текст каментария 01', "uid", "pid", "cid"
FROM users, posts, comments
WHERE "name" = 'Пользователь_8' AND "ptext" = 'Текст поста 1' AND "ctext" = 'Текст каментария 00';

INSERT INTO comments ("ctext", "userID", "postID", "perentID") 
SELECT 'Текст каментария 02', "uid", "pid", "cid"
FROM users, posts, comments
WHERE "name" = 'Пользователь_10' AND "ptext" = 'Текст поста 1' AND "ctext" = 'Текст каментария 00';

INSERT INTO comments ("ctext", "userID", "postID", "perentID") 
SELECT 'Текст каментария 012', "uid", "pid", "cid"
FROM users, posts, comments
WHERE "name" = 'Пользователь_12' AND "ptext" = 'Текст поста 1' AND "ctext" = 'Текст каментария 01';

INSERT INTO comments ("ctext", "userID", "postID", "perentID") 
SELECT 'Текст каментария 013', "uid", "pid", "cid"
FROM users, posts, comments
WHERE "name" = 'Пользователь_14' AND "ptext" = 'Текст поста 1' AND "ctext" = 'Текст каментария 012';

INSERT INTO comments ("ctext", "userID", "postID", "perentID") 
SELECT 'Текст каментария 014', "uid", "pid", "cid"
FROM users, posts, comments
WHERE "name" = 'Пользователь_16' AND "ptext" = 'Текст поста 1' AND "ctext" = 'Текст каментария 013';

INSERT INTO comments ("ctext", "userID", "postID", "perentID") 
SELECT 'Текст каментария 016', "uid", "pid", "cid"
FROM users, posts, comments
WHERE "name" = 'Пользователь_6' AND "ptext" = 'Текст поста 1' AND "ctext" = 'Текст каментария 014';


